### ISSUE TITLE
Can't start mock service wrong number of arguments (given 4, expected 2..3) (ArgumentError)

### ISSUE THREAD

**Issue by georgescumihai** [pact-foundation/pact-mock_service#102]
```
pact-mock-service start -p 1234
Traceback (most recent call last):
	11: from /Users/user/.rvm/gems/ruby-2.5.1@project/bin/ruby_executable_hooks:24:in `<main>'
	10: from /Users/user/.rvm/gems/ruby-2.5.1@project/bin/ruby_executable_hooks:24:in `eval'
	 9: from /Users/user/.rvm/gems/ruby-2.5.1@project/bin/pact-mock-service:23:in `<main>'
	 8: from /Users/user/.rvm/gems/ruby-2.5.1@project/bin/pact-mock-service:23:in `load'
	 7: from /Users/user/.rvm/gems/ruby-2.5.1@project/gems/pact-mock_service-3.0.0/bin/pact-mock-service:3:in `<top (required)>'
	 6: from /Users/user/.rvm/gems/ruby-2.5.1@project/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	 5: from /Users/user/.rvm/gems/ruby-2.5.1@project/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 4: from /Users/user/.rvm/gems/ruby-2.5.1@project/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 3: from /Users/user/.rvm/gems/ruby-2.5.1@project/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 2: from /Users/user/.rvm/gems/ruby-2.5.1@project/gems/pact-mock_service-3.0.0/lib/pact/mock_service/cli.rb:73:in `start'
	 1: from /Users/user/.rvm/gems/ruby-2.5.1@project/gems/pact-mock_service-3.0.0/lib/pact/mock_service/cli.rb:185:in `start_server'
/Users/user/.rvm/gems/ruby-2.5.1@project/gems/pact-mock_service-3.0.0/lib/pact/mock_service/server/spawn.rb:10:in `call': wrong number of arguments (given 4, expected 2..3) (ArgumentError)
```

I have version 3.0.0, installed through bundler.
```
pact-mock-service version
3.0.0
```

When ever I try to start the server, it gives me this error.

If I try with version `2.12.0`, I have no issues.

OS is MacOS 10.14.3.

**Comment by bethesque** [comment]
Fixed in 3.0.1.
